# Use root/example as user/password credentials
version: '3'
services:
  mariadb:
    container_name: "mdb_${TAG}"
    restart: always
    image: "mariadb:${TAG}"
    environment:
      - MARIADB_ROOT_PASSWORD="${PASS_ROOT}"
    ports:
      - 3303:3306
    volumes:
      - ./mariadb-data:/var/lib/mysql
