# Use root/example as user/password credentials
version: '3.08'
services:
  mysqldb:
    image: "mysql:${TAG}"
    restart: always
    container_name: "mydb_${TAG}"
    environment:
      #- MYSQL_ROOT_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD='${PASS_ROOT}'
    ports:
      - '${PORT}:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql
